FROM node:16 AS production
WORKDIR /app
COPY package.json package-lock.json ./
RUN npm install
COPY . .
RUN npm run build

# Stage 2: Serve the production build using Nginx
FROM nginx:alpine
WORKDIR /usr/share/nginx/html
COPY --from=production /app/dist .

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]